; ESP32-S3 N16R8 + 1.8" ST7735S 128x160 + 5 buttons + SPI microSD
[env:jeka725-esp32s3-st7735s]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/jeka725-esp32s3-st7735s>

build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DDEVICE_NAME='"ESP32-S3 N16R8 ST7735S"'
    -DOTA_TAG='"jeka725-esp32s3-st7735s"'
    -DROTATION=3
    -DDIMMER_SETUP=20

    -DTFT_DATABUS_N=0
    -DTFT_DISPLAY_DRIVER_N=0
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_SCLK=5
    -DTFT_MOSI=6
    -DTFT_CS=16
    -DTFT_DC=7
    -DTFT_RST=15
    -DTFT_BL=4
    -DTFT_IPS=0
    -DTFT_COL_OFS1=0
    -DTFT_ROW_OFS1=0
    -DTFT_COL_OFS2=0
    -DTFT_ROW_OFS2=0

    -DHAS_5_BUTTON=1

    -DSDCARD_CS=18
    -DSDCARD_SCK=5
    -DSDCARD_MISO=17
    -DSDCARD_MOSI=6

lib_deps =
    ${env.lib_deps}

lib_ignore =
    SensorLib
    XPowersLib
    GFX Library for Arduino
